### ISSUE TITLE
place email drafts into subfolders

### ISSUE THREAD

**Issue by victorreisenauer** [RealEst-AI/ImmoMail-Outlook-Addin#45]
Currently all drafts are saved in a folder, which is named after the respective object. 

This improvement should add two subfolders, one with all accepted emails and one with all declined emails. 

That means before that there was this naming `Folder_${currentEmailLocation}_${currentEmailObjectName}` now instead of `Folder` thre should either be `akzeptiert` or `abgelehnt`

dont forget that in the code it is impelemnted that it just goes starting from the highest rating and adds everything to the confirmationtempalte until the number of reuqest are ready than the rest goes to the rejectiontemplate

**Comment by Wladefant** [comment]
fixed with https://github.com/RealEst-AI/ImmoMail-Outlook-Addin/commit/e27c3a7341d64ba23526c8f1fc7e919beb13326f
