### ISSUE TITLE
create basic display of best rated applicants

### ISSUE THREAD

**Issue by victorreisenauer** [RealEst-AI/ImmoMail-Outlook-Addin#59]
Currently the user only sees how many applicants there are and how many emails fit their profile description (this equals the number of applicants the user wants to accept). 

We want to include a basic display of all accepted applicants, such that the user can see who will get the "accepted" email.

In the future the user should also be able reject users, which we have classified as having a good rating, and accept alternative users with also a good rating. This will be implemented in #58

**Comment by Wladefant** [comment]
implemented by https://github.com/RealEst-AI/ImmoMail-Outlook-Addin/commit/e6ec78d67142fd3682b5c294d6eac565c5e6ebea

and adjusted by https://github.com/RealEst-AI/ImmoMail-Outlook-Addin/commit/cff05c796a0e91c67f594b0e53d0348c17b7ea72
